### ISSUE TITLE
点击设置 暗色模式 点击崩溃

### ISSUE THREAD

**Issue by yanbo469** [goweii/WanAndroid#28]
2019-10-28 11:31:39.853 11773-11773/per.goweii.wanandroid E/AndroidRuntime: FATAL EXCEPTION: main
    Process: per.goweii.wanandroid, PID: 11773
    java.lang.RuntimeException: Unable to start activity ComponentInfo{per.goweii.wanandroid/per.goweii.wanandroid.module.main.activity.MainActivity}: java.lang.ClassCastException: android.view.View cannot be cast to android.view.ViewGroup
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4754)
        at android.app.ActivityThread.-wrap18(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1599)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6548)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.ClassCastException: android.view.View cannot be cast to android.view.ViewGroup
        at per.goweii.swipeback.SwipeBackLayout.findPreviousChildView(SwipeBackLayout.java:144)
        at per.goweii.swipeback.SwipeBackLayout.attachTo(SwipeBackLayout.java:131)
        at per.goweii.swipeback.SwipeBackHelper.onPostCreate(SwipeBackHelper.java:21)
        at per.goweii.swipeback.SwipeBackActivity.onPostCreate(SwipeBackActivity.java:24)
        at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1285)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2799)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4754) 
        at android.app.ActivityThread.-wrap18(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1599) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6548) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
2019-10-28 11:31:39.857 11773-11773/per.goweii.wanandroid E/CustomActivityOnCrash: App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
    java.lang.RuntimeException: Unable to start activity ComponentInfo{per.goweii.wanandroid/per.goweii.wanandroid.module.main.activity.MainActivity}: java.lang.ClassCastException: android.view.View cannot be cast to android.view.ViewGroup
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4754)
        at android.app.ActivityThread.-wrap18(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1599)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6548)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.ClassCastException: android.view.View cannot be cast to android.view.ViewGroup
        at per.goweii.swipeback.SwipeBackLayout.findPreviousChildView(SwipeBackLayout.java:144)
        at per.goweii.swipeback.SwipeBackLayout.attachTo(SwipeBackLayout.java:131)
        at per.goweii.swipeback.SwipeBackHelper.onPostCreate(SwipeBackHelper.java:21)
        at per.goweii.swipeback.SwipeBackActivity.onPostCreate(SwipeBackActivity.java:24)
        at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1285)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2799)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4754) 
        at android.app.ActivityThread.-wrap18(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1599) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6548) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by goweii** [comment]
偶发情况，周末处理

**Comment by goweii** [comment]
已修复
