### ISSUE TITLE
您好，不知道这项目您还有没有再关注，有个问题请教

### ISSUE THREAD

**Issue by SupremeQingHong** [goweii/WanAndroid#71]
在第一次安装启动的时候，这个项目出现了一个致命的错误，
--------- beginning of crash
2023-08-09 09:38:44.129 21951-22029 AndroidRuntime          com.goweii.wanandroid                E  FATAL EXCEPTION: Ponyo-Startup task pool No.1, thread No.1
Process: com.goweii.wanandroid, PID: 21951
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter t
                                                                                                    	at per.goweii.ponyo.startup.utils.DefaultPoolExecutor.afterExecute(Unknown Source:7)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1175)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
请问这个问题如何解决呢

**Comment by goweii** [comment]
你把ponyo依赖去掉吧，这是个调试工具。

**Comment by goweii** [comment]
我在1.0.0版本上修改了下（可能是修复了）
你重新拉取1.0.0版本，记得清除依赖缓存。
